const db=require('../config/db');
async function options(){return{members:await db('members').where({status:'active'}).select('id','id_no','name').orderBy('name')};}
async function summary(){const r=await db('document_records').first(db.raw("COUNT(*)::int total"),db.raw("COUNT(*) FILTER(WHERE status='draft')::int drafts"),db.raw("COUNT(*) FILTER(WHERE status='pending')::int pending"),db.raw("COUNT(*) FILTER(WHERE status IN ('approved','issued'))::int official"));return Object.fromEntries(Object.entries(r).map(([k,v])=>[k,Number(v||0)]));}
async function list(filters={}){let q=db('document_records as d').leftJoin('members as m','d.related_member_id','m.id').select('d.*','m.name as member_name');if(filters.status)q.where('d.status',filters.status);if(filters.type)q.where('d.document_type',filters.type);if(filters.q)q.where(b=>b.whereILike('d.reference_no',`%${filters.q}%`).orWhereILike('d.title',`%${filters.q}%`).orWhereILike('d.recipient_name',`%${filters.q}%`));return q.orderBy('d.issue_date','desc').orderBy('d.id','desc');}
async function create(data,userId,file){return db.transaction(async trx=>{const seq=(await trx.raw("SELECT nextval('document_reference_seq') value")).rows[0].value;const prefix=({notice:'NTC',letter:'LTR',certificate:'CRT',resolution:'RES',agreement:'AGR',other:'DOC'})[data.document_type]||'DOC';const doc=(await trx('document_records').insert({reference_no:`${prefix}-${new Date().getFullYear()}-${String(seq).padStart(6,'0')}`,document_type:data.document_type,title:data.title,subject:data.subject||null,content:data.content||null,recipient_name:data.recipient_name||null,recipient_address:data.recipient_address||null,related_member_id:data.related_member_id||null,issue_date:data.issue_date,confidentiality:data.confidentiality||'internal',created_by:userId}).returning('*'))[0];await trx('document_versions').insert({document_id:doc.id,version_no:1,title:doc.title,subject:doc.subject,content:doc.content,recipient_name:doc.recipient_name,recipient_address:doc.recipient_address,created_by:userId});await trx('document_approvals').insert({document_id:doc.id,action:'created',acted_by:userId});if(file)await trx('document_attachments').insert({document_id:doc.id,original_name:file.originalname,stored_name:file.filename,mime_type:file.mimetype,file_size:file.size,uploaded_by:userId});return doc;});}
async function find(id){const item=await db('document_records as d').leftJoin('members as m','d.related_member_id','m.id').leftJoin('users as c','d.created_by','c.id').leftJoin('users as a','d.approved_by','a.id').select('d.*','m.name as member_name','c.name as creator_name','a.name as approver_name').where('d.id',id).first();if(!item)return null;item.attachments=await db('document_attachments').where({document_id:id}).orderBy('id');item.versions=await db('document_versions as v').leftJoin('users as u','v.created_by','u.id').select('v.*','u.name as creator_name').where('v.document_id',id).orderBy('v.version_no','desc');item.approvals=await db('document_approvals as a').leftJoin('users as u','a.acted_by','u.id').select('a.*','u.name as actor_name').where('a.document_id',id).orderBy('a.acted_at','desc');return item;}
async function revise(id,data,userId,file){return db.transaction(async trx=>{const item=await trx('document_records').where({id}).forUpdate().first();if(!item||!['draft','rejected'].includes(item.status))throw new Error('Only draft or rejected documents can be edited');const version=Number(item.current_version)+1;const update={title:data.title,subject:data.subject||null,content:data.content||null,recipient_name:data.recipient_name||null,recipient_address:data.recipient_address||null,related_member_id:data.related_member_id||null,issue_date:data.issue_date,confidentiality:data.confidentiality,current_version:version,status:'draft',updated_at:trx.fn.now()};await trx('document_records').where({id}).update(update);await trx('document_versions').insert({document_id:id,version_no:version,title:update.title,subject:update.subject,content:update.content,recipient_name:update.recipient_name,recipient_address:update.recipient_address,created_by:userId});await trx('document_approvals').insert({document_id:id,action:'revised',acted_by:userId});if(file)await trx('document_attachments').insert({document_id:id,original_name:file.originalname,stored_name:file.filename,mime_type:file.mimetype,file_size:file.size,uploaded_by:userId});});}
async function transition(id,action,comments,userId){const allowed={submit:['draft','rejected'],approve:['pending'],reject:['pending'],issue:['approved'],archive:['approved','issued']};return db.transaction(async trx=>{const item=await trx('document_records').where({id}).forUpdate().first();if(!item||!allowed[action]?.includes(item.status))throw new Error('This document cannot perform that action now');const status={submit:'pending',approve:'approved',reject:'rejected',issue:'issued',archive:'archived'}[action];const update={status,updated_at:trx.fn.now()};if(action==='approve'){update.approved_by=userId;update.approved_at=trx.fn.now();}if(action==='issue')update.issued_at=trx.fn.now();await trx('document_records').where({id}).update(update);await trx('document_approvals').insert({document_id:id,action,comments:comments||null,acted_by:userId});});}
async function attachment(id){return db('document_attachments').where({id}).first();}
async function templateOptions() {
  const [members, collections, welfare, staff] = await Promise.all([
    db('members').where({ status: 'active' }).select('id', 'id_no', 'name', 'phone', 'address_text', 'father_name').orderBy('name'),
    db('collections as c').leftJoin('members as m', 'c.member_id', 'm.id').where('c.status', 'posted').select('c.id', 'c.receipt_no', 'c.amount', 'c.date', 'c.payer_name', 'c.purpose', 'm.name as member_name').orderBy('c.date', 'desc').limit(500),
    db('welfare_applications as a').join('welfare_beneficiaries as b', 'a.beneficiary_id', 'b.id').whereIn('a.status', ['approved', 'partial', 'paid']).select('a.id', 'a.application_no', 'a.assistance_type', 'a.approved_amount', 'a.disbursed_amount', 'b.name as beneficiary_name').orderBy('a.id', 'desc'),
    db('staff_members').where({ is_active: true }).select('id', 'name_bn', 'position_bn', 'joining_date', 'phone').orderBy('sort_order'),
  ]);
  return { members, collections, welfare, staff };
}

function templateData(key, source, data) {
  const common = { issue_date: data.issue_date, confidentiality: 'public', signatory_name: data.signatory_name || null, signatory_title: data.signatory_title || null, secondary_signatory_name: data.secondary_signatory_name || null, secondary_signatory_title: data.secondary_signatory_title || null };
  if (key === 'member_certificate') return { ...common, document_type: 'certificate', title: 'সদস্যপদ প্রত্যয়নপত্র', subject: 'মসজিদের সদস্যপদ ও পরিচয় প্রত্যয়ন', recipient_name: source.name, recipient_address: source.address_text, related_member_id: source.id, content: `এই মর্মে প্রত্যয়ন করা যাচ্ছে যে, ${source.name}${source.father_name ? `, পিতা: ${source.father_name}` : ''}, সদস্য নম্বর ${source.id_no}, অত্র মসজিদের একজন নিবন্ধিত ও সক্রিয় সদস্য।\n\nতাঁর আবেদনের পরিপ্রেক্ষিতে প্রয়োজনীয় কাজে ব্যবহারের জন্য এই প্রত্যয়নপত্র প্রদান করা হলো।` };
  if (key === 'donation_acknowledgement') { const donor = source.member_name || source.payer_name || 'সম্মানিত দাতা'; return { ...common, document_type: 'letter', title: 'দান প্রাপ্তির স্বীকৃতিপত্র', subject: 'দান ও সহযোগিতার জন্য কৃতজ্ঞতা', recipient_name: donor, content: `সম্মানিত ${donor},\n\nআপনার প্রদত্ত ৳ ${Number(source.amount).toFixed(2)} অনুদান আমরা কৃতজ্ঞতার সঙ্গে গ্রহণ করেছি। রশিদ নম্বর: ${source.receipt_no}।\n\nমসজিদ ও সমাজকল্যাণমূলক কার্যক্রমে আপনার সহযোগিতার জন্য আন্তরিক ধন্যবাদ। মহান আল্লাহ আপনার দান কবুল করুন।` }; }
  if (key === 'welfare_approval') return { ...common, document_type: 'letter', title: 'সহায়তা অনুমোদনপত্র', subject: `আবেদন ${source.application_no} অনুমোদন`, recipient_name: source.beneficiary_name, content: `আপনার ${source.assistance_type} সহায়তার আবেদন (${source.application_no}) পর্যালোচনার পর ৳ ${Number(source.approved_amount).toFixed(2)} অনুমোদন করা হয়েছে।\n\nপ্রয়োজনীয় পরিচয় ও কাগজপত্রসহ মসজিদ কার্যালয়ে যোগাযোগ করার জন্য অনুরোধ করা হলো।`, confidentiality: 'confidential' };
  if (key === 'staff_certificate') return { ...common, document_type: 'certificate', title: 'কর্মরত থাকার প্রত্যয়নপত্র', subject: 'চাকরি ও দায়িত্ব প্রত্যয়ন', recipient_name: source.name_bn, content: `এই মর্মে প্রত্যয়ন করা যাচ্ছে যে, ${source.name_bn} অত্র মসজিদে ${source.position_bn || 'স্টাফ'} পদে দায়িত্ব পালন করছেন।\n\nতাঁর আবেদনের পরিপ্রেক্ষিতে প্রয়োজনীয় কাজে ব্যবহারের জন্য এই প্রত্যয়নপত্র প্রদান করা হলো।` };
  return { ...common, document_type: 'letter', title: data.title || 'সাধারণ পত্র', subject: data.subject || null, recipient_name: data.recipient_name || null, recipient_address: data.recipient_address || null, content: data.content || '' };
}

async function createFromTemplate(data, userId) {
  return db.transaction(async (trx) => {
    let source = null; let sourceType = null;
    if (data.template_key === 'member_certificate') { sourceType = 'member'; source = await trx('members').where({ id: data.source_id, status: 'active' }).first(); }
    else if (data.template_key === 'donation_acknowledgement') { sourceType = 'collection'; source = await trx('collections as c').leftJoin('members as m', 'c.member_id', 'm.id').select('c.*', 'm.name as member_name').where('c.id', data.source_id).where('c.status', 'posted').first(); }
    else if (data.template_key === 'welfare_approval') { sourceType = 'welfare'; source = await trx('welfare_applications as a').join('welfare_beneficiaries as b', 'a.beneficiary_id', 'b.id').select('a.*', 'b.name as beneficiary_name').where('a.id', data.source_id).whereIn('a.status', ['approved', 'partial', 'paid']).first(); }
    else if (data.template_key === 'staff_certificate') { sourceType = 'staff'; source = await trx('staff_members').where({ id: data.source_id, is_active: true }).first(); }
    else if (data.template_key !== 'general_letter') throw new Error('সঠিক টেমপ্লেট নির্বাচন করুন');
    if (data.template_key !== 'general_letter' && !source) throw new Error('নির্বাচিত উৎস রেকর্ড পাওয়া যায়নি');
    const generated = templateData(data.template_key, source, data);
    const seq = (await trx.raw("SELECT nextval('document_reference_seq') value")).rows[0].value;
    const prefix = generated.document_type === 'certificate' ? 'CRT' : 'LTR';
    const [doc] = await trx('document_records').insert({ ...generated, reference_no: `${prefix}-${new Date().getFullYear()}-${String(seq).padStart(6, '0')}`, template_key: data.template_key, source_type: sourceType, source_id: source ? source.id : null, source_snapshot: source || null, status: 'draft', current_version: 1, created_by: userId }).returning('*');
    await trx('document_versions').insert({ document_id: doc.id, version_no: 1, title: doc.title, subject: doc.subject, content: doc.content, recipient_name: doc.recipient_name, recipient_address: doc.recipient_address, created_by: userId });
    await trx('document_approvals').insert({ document_id: doc.id, action: 'created', comments: `Generated from ${data.template_key}`, acted_by: userId });
    return doc;
  });
}
module.exports={options,summary,list,create,find,revise,transition,attachment,templateOptions,createFromTemplate};
