const db=require('../config/db');
function dates(query,column,from,to){if(from)query.where(column,'>=',from);if(to)query.where(column,'<=',to);return query;}
async function procurement(from,to){const payments=db('purchase_payments').select('purchase_order_id').sum('amount as paid').groupBy('purchase_order_id').as('pay');const q=db('purchase_orders as o').join('purchase_requests as r','o.request_id','r.id').join('maintenance_vendors as v','o.vendor_id','v.id').leftJoin(payments,'o.id','pay.purchase_order_id').select('o.*','r.request_no','r.title as request_title','v.name as vendor_name',db.raw('COALESCE(pay.paid,0) as paid'));dates(q,'o.order_date',from,to);const rows=await q.orderBy('o.order_date','desc');return{rows,summary:{count:rows.length,total:rows.reduce((s,x)=>s+Number(x.order_total),0),paid:rows.reduce((s,x)=>s+Number(x.paid),0)}};}
async function inventory(from,to){const q=db('inventory_movements as m').join('inventory_items as i','m.item_id','i.id').leftJoin('staff_members as s','m.issued_to_staff_id','s.id').leftJoin('facilities as f','m.facility_id','f.id').leftJoin('mosque_programs as p','m.program_id','p.id').select('m.*','i.item_code','i.name as item_name','i.unit','s.name_bn as staff_name','f.name as facility_name','p.name as program_name');dates(q,'m.movement_date',from,to);const rows=await q.orderBy('m.movement_date','desc').orderBy('m.id','desc');return{rows,summary:{count:rows.length,received:rows.filter(x=>x.movement_type==='receipt').reduce((s,x)=>s+Number(x.quantity),0),issued:Math.abs(rows.filter(x=>x.movement_type==='issue').reduce((s,x)=>s+Number(x.quantity),0)),value:rows.filter(x=>x.movement_type==='receipt').reduce((s,x)=>s+Number(x.quantity)*Number(x.unit_cost),0)}};}
async function maintenance(from,to){const q=db('maintenance_work_orders as w').leftJoin('assets as a','w.asset_id','a.id').leftJoin('facilities as f','w.facility_id','f.id').leftJoin('maintenance_vendors as v','w.vendor_id','v.id').select('w.*','a.name as asset_name','a.asset_code','f.name as facility_name','v.name as vendor_name');dates(q,'w.reported_date',from,to);const rows=await q.orderBy('w.reported_date','desc');return{rows,summary:{count:rows.length,open:rows.filter(x=>!['completed','cancelled'].includes(x.status)).length,estimated:rows.reduce((s,x)=>s+Number(x.estimated_cost),0),actual:rows.reduce((s,x)=>s+Number(x.actual_cost),0)}};}
async function welfare(from,to){const q=db('welfare_applications as a').join('welfare_beneficiaries as b','a.beneficiary_id','b.id').select('a.*','b.name as beneficiary_name','b.phone');if(from)q.where('a.created_at','>=',from);if(to)q.where('a.created_at','<',db.raw("?::date + INTERVAL '1 day'",[to]));const rows=await q.orderBy('a.created_at','desc');return{rows,summary:{count:rows.length,pending:rows.filter(x=>x.status==='pending').length,approved:rows.reduce((s,x)=>s+Number(x.approved_amount||0),0),disbursed:rows.reduce((s,x)=>s+Number(x.disbursed_amount||0),0)}};}
async function payroll(from,to){const q=db('staff_payrolls as p').join('staff_members as s','p.staff_id','s.id').select('p.*','s.name_bn as staff_name','s.position_bn');dates(q,'p.payroll_month',from,to);const rows=await q.orderBy('p.payroll_month','desc').orderBy('s.sort_order');return{rows,summary:{count:rows.length,payable:rows.reduce((s,x)=>s+Number(x.net_payable),0),paid:rows.reduce((s,x)=>s+Number(x.amount_paid),0),outstanding:rows.reduce((s,x)=>s+Number(x.net_payable)-Number(x.amount_paid),0)}};}
async function programs(from,to){const attendance=db('program_attendance').select('program_id').count('* as sessions').countDistinct('attendance_date as class_days').whereIn('status',['present','late']).modify(q=>dates(q,'attendance_date',from,to)).groupBy('program_id').as('att');const enrollment=db('program_enrollments').where({status:'active'}).select('program_id').count('* as enrolled').groupBy('program_id').as('en');const rows=await db('mosque_programs as p').leftJoin(attendance,'p.id','att.program_id').leftJoin(enrollment,'p.id','en.program_id').select('p.*',db.raw('COALESCE(en.enrolled,0)::int as enrolled'),db.raw('COALESCE(att.sessions,0)::int as attendance_marks'),db.raw('COALESCE(att.class_days,0)::int as class_days')).orderBy('p.name');return{rows,summary:{count:rows.length,active:rows.filter(x=>x.status==='active').length,enrolled:rows.reduce((s,x)=>s+Number(x.enrolled),0),attendance:rows.reduce((s,x)=>s+Number(x.attendance_marks),0)}};}
async function governance(from,to){const resolutions=db('meeting_resolutions').select('meeting_id').count('* as resolutions').groupBy('meeting_id').as('r');const actions=db('meeting_action_items').select('meeting_id',db.raw('COUNT(*)::int as actions'),db.raw("COUNT(*) FILTER (WHERE status IN ('open','in_progress','blocked'))::int as open_actions")).groupBy('meeting_id').as('a');const q=db('committee_meetings as m').join('committees as c','m.committee_id','c.id').leftJoin(resolutions,'m.id','r.meeting_id').leftJoin(actions,'m.id','a.meeting_id').select('m.*','c.name as committee_name',db.raw('COALESCE(r.resolutions,0)::int as resolution_count'),db.raw('COALESCE(a.actions,0)::int as action_count'),db.raw('COALESCE(a.open_actions,0)::int as open_action_count'));dates(q,'m.meeting_date',from,to);const rows=await q.orderBy('m.meeting_date','desc');return{rows,summary:{count:rows.length,held:rows.filter(x=>x.status==='held').length,resolutions:rows.reduce((s,x)=>s+Number(x.resolution_count),0),openActions:rows.reduce((s,x)=>s+Number(x.open_action_count),0)}};}
const handlers={procurement,inventory,maintenance,welfare,payroll,programs,governance};
async function generate(type,{from,to}){if(!handlers[type])throw new Error('Invalid operational report');return handlers[type](from,to);}
module.exports={generate,types:Object.keys(handlers)};
