const db = require('../config/db');
function apply(q, filters, alias = 't') { if (filters.from) q.where(`${alias}.created_at`, '>=', filters.from); if (filters.to) q.where(`${alias}.created_at`, '<', db.raw("?::date + INTERVAL '1 day'", [filters.to])); if (filters.category) q.where(`${alias}.category`, filters.category); if (filters.assigned_user_id) q.where(`${alias}.assigned_user_id`, filters.assigned_user_id); return q; }
async function generate(filters = {}) {
  const base = apply(db('mosque_tasks as t').leftJoin('users as u', 't.assigned_user_id', 'u.id').select('t.*', 'u.name as assigned_name'), filters);
  const rows = await base.orderBy('t.created_at', 'desc');
  const total = rows.length; const completed = rows.filter((x) => x.status === 'completed').length; const active = rows.filter((x) => ['open', 'in_progress', 'blocked'].includes(x.status)).length; const overdue = rows.filter((x) => x.due_date && new Date(x.due_date) < new Date() && ['open', 'in_progress', 'blocked'].includes(x.status)).length;
  const completionRate = total ? Math.round(completed / total * 100) : 0;
  const completedWithDates = rows.filter((x) => x.status === 'completed' && x.completed_at && x.created_at); const averageDays = completedWithDates.length ? Math.round(completedWithDates.reduce((sum, x) => sum + Math.max(0, (new Date(x.completed_at) - new Date(x.created_at)) / 86400000), 0) / completedWithDates.length * 10) / 10 : 0;
  const categories = [...new Set(rows.map((x) => x.category))].map((category) => { const categoryRows = rows.filter((x) => x.category === category); const done = categoryRows.filter((x) => x.status === 'completed').length; return { category, total: categoryRows.length, completed: done, overdue: categoryRows.filter((x) => x.due_date && new Date(x.due_date) < new Date() && ['open', 'in_progress', 'blocked'].includes(x.status)).length, rate: categoryRows.length ? Math.round(done / categoryRows.length * 100) : 0 }; }).sort((a, b) => b.total - a.total);
  const workloadRows = rows.filter((x) => ['open', 'in_progress', 'blocked'].includes(x.status)); const names = [...new Set(workloadRows.map((x) => x.assigned_name || 'অনির্ধারিত'))]; const workload = names.map((name) => { const assigned = workloadRows.filter((x) => (x.assigned_name || 'অনির্ধারিত') === name); return { name, total: assigned.length, overdue: assigned.filter((x) => x.due_date && new Date(x.due_date) < new Date()).length, critical: assigned.filter((x) => x.priority === 'critical').length }; }).sort((a, b) => b.total - a.total);
  const trend = []; const now = new Date(); for (let offset = 5; offset >= 0; offset -= 1) { const date = new Date(now.getFullYear(), now.getMonth() - offset, 1); const key = `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, '0')}`; trend.push({ month: key, created: rows.filter((x) => String(x.created_at).slice(0, 7) === key || (x.created_at instanceof Date && `${x.created_at.getFullYear()}-${String(x.created_at.getMonth() + 1).padStart(2, '0')}` === key)).length, completed: rows.filter((x) => x.completed_at && (String(x.completed_at).slice(0, 7) === key || (x.completed_at instanceof Date && `${x.completed_at.getFullYear()}-${String(x.completed_at.getMonth() + 1).padStart(2, '0')}` === key))).length }); }
  return { rows, summary: { total, completed, active, overdue, completionRate, averageDays }, categories, workload, trend };
}
function csv(data) { const escape = (value) => `"${String(value == null ? '' : value).replace(/"/g, '""')}"`; const lines = [['Task No', 'Title', 'Category', 'Priority', 'Assignee', 'Start Date', 'Due Date', 'Status', 'Created At'], ...data.rows.map((x) => [x.task_no, x.title, x.category, x.priority, x.assigned_name || '', x.start_date || '', x.due_date || '', x.status, x.created_at])]; return `\uFEFF${lines.map((line) => line.map(escape).join(',')).join('\r\n')}`; }
module.exports = { generate, csv };
