exports.up=async(knex)=>{
  await knex.schema.alterTable('staff_members',t=>{t.decimal('basic_salary',14,2).notNullable().defaultTo(0);t.string('employment_status').notNullable().defaultTo('active');});
  await knex.schema.createTable('staff_duty_rosters',t=>{t.increments('id').primary();t.integer('staff_id').notNullable().references('id').inTable('staff_members').onDelete('CASCADE');t.string('day_of_week').notNullable();t.time('start_time').notNullable();t.time('end_time').notNullable();t.string('duty_name').notNullable();t.string('location');t.boolean('is_active').notNullable().defaultTo(true);t.timestamps(true,true);t.index(['staff_id','day_of_week']);});
  await knex.schema.createTable('staff_attendance',t=>{t.bigIncrements('id').primary();t.integer('staff_id').notNullable().references('id').inTable('staff_members').onDelete('CASCADE');t.date('attendance_date').notNullable();t.time('check_in');t.time('check_out');t.string('status').notNullable().defaultTo('present');t.text('remarks');t.integer('recorded_by').references('id').inTable('users').onDelete('SET NULL');t.timestamps(true,true);t.unique(['staff_id','attendance_date']);t.index(['attendance_date','status']);});
  await knex.schema.createTable('staff_payrolls',t=>{t.bigIncrements('id').primary();t.integer('staff_id').notNullable().references('id').inTable('staff_members').onDelete('RESTRICT');t.date('payroll_month').notNullable();t.decimal('basic_salary',14,2).notNullable().defaultTo(0);t.decimal('allowances',14,2).notNullable().defaultTo(0);t.decimal('deductions',14,2).notNullable().defaultTo(0);t.decimal('net_payable',14,2).notNullable().defaultTo(0);t.decimal('amount_paid',14,2).notNullable().defaultTo(0);t.string('status').notNullable().defaultTo('unpaid');t.text('notes');t.integer('generated_by').references('id').inTable('users').onDelete('SET NULL');t.timestamps(true,true);t.unique(['staff_id','payroll_month']);t.index(['payroll_month','status']);});
  await knex.schema.createTable('staff_payroll_payments',t=>{t.bigIncrements('id').primary();t.bigInteger('payroll_id').notNullable().references('id').inTable('staff_payrolls').onDelete('RESTRICT');t.integer('expense_id').references('id').inTable('expenses').onDelete('SET NULL');t.decimal('amount',14,2).notNullable();t.date('payment_date').notNullable();t.string('payment_method').notNullable().defaultTo('cash');t.string('reference');t.text('remarks');t.integer('paid_by').references('id').inTable('users').onDelete('SET NULL');t.timestamp('created_at').notNullable().defaultTo(knex.fn.now());});
  if(!await knex('expense_heads').where({name:'স্টাফ বেতন ও ভাতা'}).first())await knex('expense_heads').insert({name:'স্টাফ বেতন ও ভাতা'});
};
exports.down=async(knex)=>{await knex.schema.dropTableIfExists('staff_payroll_payments');await knex.schema.dropTableIfExists('staff_payrolls');await knex.schema.dropTableIfExists('staff_attendance');await knex.schema.dropTableIfExists('staff_duty_rosters');await knex.schema.alterTable('staff_members',t=>t.dropColumns('basic_salary','employment_status'));await knex('expense_heads').where({name:'স্টাফ বেতন ও ভাতা'}).del();};
